"""empty message

Revision ID: 156d16e4c9d1
Revises: 17a846354be9
Create Date: 2025-03-10 17:20:16.570710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156d16e4c9d1'
down_revision = '17a846354be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('captcha_token', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
