"""empty message

Revision ID: 97762335add0
Revises: 156d16e4c9d1
Create Date: 2025-03-11 10:04:31.639513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97762335add0'
down_revision = '156d16e4c9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.drop_index('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
